// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconCompleted(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <circle cx={12} cy={12} r={9} fill="currentColor" /><path fill="currentColor" d="m17.53 9.53-6.146 6.147a1.25 1.25 0 0 1-1.768 0L6.47 12.53l1.06-1.06 2.97 2.97 5.97-5.97z" />
    </IconBase>
  )
}

IconCompleted.displayName = "IconCompleted"
