// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconUndo(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="m12.243 8 1.06 1.06-3.182 3.183 3.182 3.182-1.06 1.06L8 12.243z" /><path fill="currentColor" d="M16 11.25v1.5h-6v-1.5z" /><path fill="currentColor" d="M19.5 12a7.5 7.5 0 1 0-7.5 7.5V21a9 9 0 1 1 0-18 9 9 0 0 1 0 18v-1.5a7.5 7.5 0 0 0 7.5-7.5" />
    </IconBase>
  )
}

IconUndo.displayName = "IconUndo"
