// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconVideoclarity(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" clipPath="url(#a)"><path d="M4.5 18h15V9.284L15.467 6H4.5zM21 19l-.01.1a.5.5 0 0 1-.49.4h-17A.5.5 0 0 1 3 19V5a.5.5 0 0 1 .5-.5H16l4.815 3.92a.5.5 0 0 1 .185.39z" /><path d="M8.75 11.25h1.5V9h1.5v6h-1.5v-2.25h-1.5V15h-1.5V9h1.5zM13 9c2.21 0 4 1 4 3s-1.79 3-4 3zm1.25 4.5a1.5 1.5 0 0 0 0-3z" /></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h24v24H0z" /></clipPath></defs>
    </IconBase>
  )
}

IconVideoclarity.displayName = "IconVideoclarity"
