// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function Iconplayspeed(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <g stroke="#F5F5F7" strokeWidth={1.5} clipPath="url(#a)"><path d="M4.75 17.466V6.534L11.778 12zM12.75 17.466V6.534L19.778 12z" /></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h24v24H0z" /></clipPath></defs>
    </IconBase>
  )
}

Iconplayspeed.displayName = "Iconplayspeed"
