// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconArchive(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M14 6h6a.5.5 0 0 1 .5.5V10H19V7.5h-5.389L9.111 5H5v14h5v1.5H4a.5.5 0 0 1-.5-.5V4a.5.5 0 0 1 .5-.5h5.5z" /><path fill="currentColor" d="m12.44 13.498 6 7 1.12-.996-6-7z" /><path fill="currentColor" d="M12 18h1.5v-4.5H18V12h-6z" />
    </IconBase>
  )
}

IconArchive.displayName = "IconArchive"
