// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconClean(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M10 4.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V8h5a.5.5 0 0 1 .5.5v3a.5.5 0 0 1-.5.5H5a.5.5 0 0 1-.5-.5v-3A.5.5 0 0 1 5 8h5z" clipRule="evenodd" /><path stroke="currentColor" strokeLinejoin="round" strokeWidth={1.5} d="M6 19.5a.5.5 0 0 0 .5.5h11a.5.5 0 0 0 .5-.5V12H6v7.5ZM12 19.992V17" />
    </IconBase>
  )
}

IconClean.displayName = "IconClean"
