// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconArrowRight(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path d="M5 12h14M13 6l6 6-6 6" />
    </IconBase>
  )
}

IconArrowRight.displayName = "IconArrowRight"
