// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconConfirm(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="#F5F5F7" d="m16.555 9.505-4.648 5.111a1.25 1.25 0 0 1-1.808.043l-2.63-2.629 1.061-1.06 2.444 2.443 4.471-4.918z" /><circle cx={12} cy={12} r={8.25} stroke="#F5F5F7" strokeWidth={1.5} />
    </IconBase>
  )
}

IconConfirm.displayName = "IconConfirm"
