// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function Iconselected(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <rect width={14} height={14} x={5} y={5} fill="currentColor" rx={0.5} /><path stroke="#F5F5F7" strokeWidth={1.5} d="M8.5 11.5 11 14l4.5-4.5" />
    </IconBase>
  )
}

Iconselected.displayName = "Iconselected"
