// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconText(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M17.5 19.5h-11V7.736L9.538 4.5H17.5zM5 20.5a.5.5 0 0 0 .5.5h13l.1-.01a.5.5 0 0 0 .4-.49v-17a.5.5 0 0 0-.5-.5H8.889L5.136 6.999A.5.5 0 0 0 5 7.341z" /><path fill="currentColor" d="M15 10.25v1.5H9v-1.5zM15 14.25v1.5H9v-1.5z" />
    </IconBase>
  )
}

IconText.displayName = "IconText"
