// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconFreeLayout(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <mask id="a" fill="#fff"><rect width={16} height={7} x={11} y={4} rx={0.5} transform="rotate(90 11 4)" /></mask><rect width={16} height={7} x={11} y={4} stroke="currentColor" strokeWidth={3} mask="url(#a)" rx={0.5} transform="rotate(90 11 4)" /><mask id="b" fill="#fff"><rect width={7} height={7} x={20} y={4} rx={0.5} transform="rotate(90 20 4)" /></mask><rect width={7} height={7} x={20} y={4} stroke="currentColor" strokeWidth={3} mask="url(#b)" rx={0.5} transform="rotate(90 20 4)" /><path fill="currentColor" d="M17.25 13v7h-1.5v-7z" /><path fill="currentColor" d="M20 17.25h-7v-1.5h7z" />
    </IconBase>
  )
}

IconFreeLayout.displayName = "IconFreeLayout"
