// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconCredits(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="#F5F5F7" d="M19.25 9a5.25 5.25 0 1 0-10.5 0 5.25 5.25 0 0 0 10.5 0m1.5 0a6.75 6.75 0 1 1-13.5 0 6.75 6.75 0 0 1 13.5 0" /><path fill="#F5F5F7" d="M6 8.166q.002.745.122 1.455a5.25 5.25 0 1 0 7.172 7.172q.712.122 1.456.123.082-.002.165-.005A6.748 6.748 0 0 1 2 14.166 6.75 6.75 0 0 1 6.004 8Q6 8.082 6 8.166" /><path fill="#F5F5F7" d="m8.768 12 1.768 1.768-1.768 1.768L7 13.768zM13.968 7.2l1.768 1.768-1.768 1.768L12.2 8.968z" />
    </IconBase>
  )
}

IconCredits.displayName = "IconCredits"
