// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSearch(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <circle cx={7} cy={7} r={6.25} stroke="#F5F5F7" strokeWidth={1.5} transform="scale(-1 1)rotate(-42.714 2.03 34.38)" /><path fill="currentColor" d="m8.243 15 1.06 1.06-4.242 4.243L4 19.243z" />
    </IconBase>
  )
}

IconSearch.displayName = "IconSearch"
