// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconExpandGroup(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20 4.25v1.5H4v-1.5zM20 14.56l-7.232 4.794-.087.061a1.25 1.25 0 0 1-1.362 0l-.087-.061L4 14.56v-1.796l8 5.286 8-5.286z" /><path fill="currentColor" d="m20 9.796-7.232 4.794-.087.061a1.25 1.25 0 0 1-1.362 0l-.087-.061L4 9.796V8l8 5.286L20 8z" />
    </IconBase>
  )
}

IconExpandGroup.displayName = "IconExpandGroup"
