// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconAvailableToView(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M12 5c4.97 0 9 5.833 9 7l-.012.123C20.747 13.526 16.815 19 12 19v-1.5c1.911 0 3.802-1.144 5.311-2.63a12.5 12.5 0 0 0 1.718-2.094c.198-.309.335-.563.416-.747q.006-.015.011-.029l-.01-.03a6 6 0 0 0-.417-.746 12.5 12.5 0 0 0-1.718-2.093C15.801 7.644 13.911 6.5 12 6.5S8.198 7.644 6.688 9.13a12.5 12.5 0 0 0-1.717 2.094 6 6 0 0 0-.416.747L4.543 12l.012.03c.08.183.218.437.416.746.395.617.982 1.37 1.717 2.093 1.51 1.487 3.4 2.631 5.312 2.631V19l-.232-.004C6.904 18.82 3 13.148 3 12c0-1.167 4.03-7 9-7" /><path fill="currentColor" d="M13.5 12a1.5 1.5 0 1 0-1.5 1.5V15a3 3 0 1 1 0-6 3 3 0 0 1 0 6v-1.5a1.5 1.5 0 0 0 1.5-1.5" />
    </IconBase>
  )
}

IconAvailableToView.displayName = "IconAvailableToView"
