// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconNotification(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M14.5 18a2.5 2.5 0 0 1-5 0H11a1 1 0 1 0 2 0zM15.5 9a3.5 3.5 0 1 0-7 0v5.5h7zm1.5 7H7V9a5 5 0 0 1 10 0z" /><path fill="currentColor" d="M19 14.75v1.5H5v-1.5z" />
    </IconBase>
  )
}

IconNotification.displayName = "IconNotification"
