// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconEraser(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="currentColor" strokeWidth={1.5} d="m20.324 11.778-6.675 6.675H7.907L4.06 14.607l9.546-9.546z" /><path fill="currentColor" d="m12.084 14.443-1.06 1.06-1.415-1.414 1.06-1.06z" />
    </IconBase>
  )
}

IconEraser.displayName = "IconEraser"
