// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconGenerationHistory(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="#F5F5F7" d="M3.183 10.523a.85.85 0 0 0 1.04.5l.089-.034L7.3 9.69l-.6-1.377-2.297 1.001-.68-2.51L3 7l-.724.196.876 3.236z" /><path fill="#F5F5F7" d="M5.014 9.994a7.75 7.75 0 1 1-.001 4.012l-.725.195-.724.194a9.25 9.25 0 1 0 .001-4.789z" /><path fill="#F5F5F7" d="M12.75 8v5.536l2.585 1.293-.67 1.342-3-1.5A.75.75 0 0 1 11.25 14V8z" />
    </IconBase>
  )
}

IconGenerationHistory.displayName = "IconGenerationHistory"
