// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconObjectMovement(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M11.25 3.6v6.072h1.5V3.6zM11.25 20.321V14.25h1.5v6.071zM3.6 11.036h6.072v1.5H3.6zM20.321 11.036H14.25v1.5h6.071z" /><path fill="currentColor" d="M12.354 2.854a.5.5 0 0 0-.708 0L8.464 6.036l1.061 1.06L12 4.621l2.475 2.475 1.06-1.06zM12.354 21.068a.5.5 0 0 1-.708 0l-3.182-3.182 1.061-1.06L12 19.3l2.475-2.475 1.06 1.061zM2.854 12.139a.5.5 0 0 1 0-.707L6.036 8.25l1.06 1.06-2.475 2.475 2.475 2.475-1.06 1.061zM21.068 12.139a.5.5 0 0 0 0-.707L17.886 8.25l-1.06 1.06 2.474 2.475-2.475 2.475 1.06 1.061z" />
    </IconBase>
  )
}

IconObjectMovement.displayName = "IconObjectMovement"
