// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSeparatorLine(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20 11.25v1.5H4v-1.5zM14 18.25v1.5h-4v-1.5zM20 18.25v1.5h-4v-1.5zM14 4.25v1.5h-4v-1.5zM8 18.25v1.5H4v-1.5zM8 4.25v1.5H4v-1.5zM20 4.25v1.5h-4v-1.5z" />
    </IconBase>
  )
}

IconSeparatorLine.displayName = "IconSeparatorLine"
