// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconDrag(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <rect width={3} height={3} x={7.5} y={4.5} fill="currentColor" rx={0.5} /><rect width={3} height={3} x={7.5} y={10.5} fill="currentColor" rx={0.5} /><rect width={3} height={3} x={7.5} y={16.5} fill="currentColor" rx={0.5} /><rect width={3} height={3} x={13.5} y={4.5} fill="currentColor" rx={0.5} /><rect width={3} height={3} x={13.5} y={10.5} fill="currentColor" rx={0.5} /><rect width={3} height={3} x={13.5} y={16.5} fill="currentColor" rx={0.5} />
    </IconBase>
  )
}

IconDrag.displayName = "IconDrag"
