// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSticker(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M5.5 4.5h13v11.764L15.462 19.5H5.5zm14.5-1a.5.5 0 0 0-.5-.5h-15l-.1.01a.5.5 0 0 0-.4.49v17a.5.5 0 0 0 .5.5h11.611l3.753-3.999a.5.5 0 0 0 .136-.342z" /><path fill="currentColor" d="M19.75 14.75v1.5h-4v4h-1.5V15.5a.75.75 0 0 1 .75-.75zM16 8.5V10H8V8.5z" />
    </IconBase>
  )
}

IconSticker.displayName = "IconSticker"
