// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconRecordkeyframes(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M10 3.5a.5.5 0 0 1 .5-.5h3a.5.5 0 0 1 .5.5V4a.5.5 0 0 1-.5.5h-3A.5.5 0 0 1 10 4z" /><path fill="currentColor" d="M11.75 7a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5h.5a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5zM15.433 7.848a.5.5 0 0 1-.183-.683l1-1.732a.5.5 0 0 1 .683-.183l.433.25a.5.5 0 0 1 .183.683l-1 1.732a.5.5 0 0 1-.683.183z" /><circle cx={12} cy={13.5} r={6.75} stroke="currentColor" strokeWidth={1.5} /><path fill="currentColor" d="m12 12 1.414 1.414L12 14.828l-1.414-1.414z" />
    </IconBase>
  )
}

IconRecordkeyframes.displayName = "IconRecordkeyframes"
