// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconKeyframe(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M11.693 5.627a.433.433 0 0 1 .613 0l6.067 6.066a.433.433 0 0 1 0 .613l-6.067 6.067a.433.433 0 0 1-.613 0l-6.066-6.067a.433.433 0 0 1 0-.613z" />
    </IconBase>
  )
}

IconKeyframe.displayName = "IconKeyframe"
