// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSaveToAssets(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M17.378 20.657h-1.5V13h1.5z" /><path fill="currentColor" d="M20.457 17.578H12.8v-1.5h7.657z" /><path fill="currentColor" d="M14 6h6a.5.5 0 0 1 .5.5V10H19V7.5h-5.389l-.34-.188L9.112 5H5v14h5v1.5H4a.5.5 0 0 1-.5-.5V4a.5.5 0 0 1 .5-.5h5.5z" />
    </IconBase>
  )
}

IconSaveToAssets.displayName = "IconSaveToAssets"
