// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconH2(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M15.93 19.54a.5.5 0 0 1-.5-.5v-.126c0-.142.061-.278.167-.374q.903-.815 1.553-1.52.72-.77 1.1-1.43.38-.67.38-1.24 0-.36-.13-.63a.9.9 0 0 0-.38-.41q-.24-.15-.6-.15-.4 0-.74.23-.122.081-.236.174c-.22.178-.542.194-.746-.002l-.095-.091c-.196-.19-.207-.504-.003-.685a3.5 3.5 0 0 1 .71-.496q.55-.29 1.3-.29.7 0 1.22.29.53.28.82.79t.29 1.2q0 .67-.34 1.37-.33.69-.89 1.38t-1.24 1.36q.29-.04.62-.06.34-.03.6-.03h1.1a.5.5 0 0 1 .5.5v.24a.5.5 0 0 1-.5.5z" /><path fill="currentColor" d="M13 12.75H5v-1.5h8z" /><path fill="currentColor" d="M13.25 4a.5.5 0 0 1 .5.5v15a.5.5 0 0 1-.5.5h-.5a.5.5 0 0 1-.5-.5v-15a.5.5 0 0 1 .5-.5zM5 4a.5.5 0 0 1 .5.5v15a.5.5 0 0 1-.5.5h-.5a.5.5 0 0 1-.5-.5v-15a.5.5 0 0 1 .5-.5z" />
    </IconBase>
  )
}

IconH2.displayName = "IconH2"
