// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconElementLayout(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M18.5 7.5a2 2 0 1 0-2 2V11a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7V9.5a2 2 0 0 0 2-2M14.5 18.5h4v-4h-4zm5.5 1a.5.5 0 0 1-.5.5h-6a.5.5 0 0 1-.5-.5v-6a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 .5.5zM5.5 9.5h4v-4h-4zm5.5 1a.5.5 0 0 1-.5.5h-6a.5.5 0 0 1-.5-.5v-6a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 .5.5zM7.064 12.774a.5.5 0 0 1 .872 0l3.645 6.48a.5.5 0 0 1-.366.741l-.07.005h-7.29a.5.5 0 0 1-.436-.745zm-1.5 5.726h3.872L7.5 15.059z" />
    </IconBase>
  )
}

IconElementLayout.displayName = "IconElementLayout"
