// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconCheck(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path d="m5 12.5 5 5L19 7" />
    </IconBase>
  )
}

IconCheck.displayName = "IconCheck"
