// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconObjectRotation(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="m1.621 12.095.923-1.188 1.885 1.466 1.466-1.886 1.189.923-2.39 3.074zM22.475 11.35l-.896 1.207-1.917-1.423-1.424 1.918-1.208-.897 2.32-3.125zM12.021 9.9l2.121 2.121-2.12 2.121-2.122-2.12z" /><path fill="currentColor" d="M12.25 3a8.73 8.73 0 0 1 6.708 3.134l-.969 1.188A7.25 7.25 0 0 0 5.282 13.75h-1.55A8.75 8.75 0 0 1 12.25 3M11.708 20.75A8.73 8.73 0 0 1 5 17.616l.969-1.188A7.25 7.25 0 0 0 18.676 10h1.55a8.75 8.75 0 0 1-8.518 10.75" />
    </IconBase>
  )
}

IconObjectRotation.displayName = "IconObjectRotation"
