// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconPaintBucket(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" fillRule="evenodd" d="M18.5 21c.828 0 1.5-.716 1.5-1.6q0-.885-1.5-2.4-1.5 1.515-1.5 2.4c0 .884.672 1.6 1.5 1.6" clipRule="evenodd" /><path fill="currentColor" d="m12.662 5.237-1.06 1.06L9.833 4.53l1.06-1.06z" /><path fill="currentColor" d="M10.89 5.242a1.25 1.25 0 0 1 1.684-.076l.095.087 5.96 6.118a1.25 1.25 0 0 1-.01 1.756l-7.071 7.071a1.25 1.25 0 0 1-1.78-.011l-5.96-6.118a1.25 1.25 0 0 1 .01-1.756zm-5.836 7.956 5.612 5.76 6.717-6.718-5.611-5.76z" /><path fill="currentColor" d="M5.296 11.24a.75.75 0 0 1 .964-.444l9.5 3.5a.751.751 0 0 1-.52 1.408l-9.5-3.5a.75.75 0 0 1-.444-.964" />
    </IconBase>
  )
}

IconPaintBucket.displayName = "IconPaintBucket"
