// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconFindreference(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M19.864 6.999a.5.5 0 0 1 .136.342V20.5a.5.5 0 0 1-.5.5H13v-1.5h5.5V7.736L15.462 4.5H7.5V8H6V3.5a.5.5 0 0 1 .5-.5h9.611z" /><path stroke="#F5F5F7" strokeWidth={1.5} d="M10.741 16.384a3 3 0 1 1-.913-5.93 3 3 0 0 1 .913 5.93Z" /><path stroke="#F5F5F7" strokeLinejoin="round" strokeWidth={1.5} d="m8.118 15.776-3.584 4.093" />
    </IconBase>
  )
}

IconFindreference.displayName = "IconFindreference"
