// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconBoldText(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M16.25 15.25a2.75 2.75 0 0 0-2.75-2.75H7V11h6.5a4.25 4.25 0 0 1 0 8.5H7V18h6.5a2.75 2.75 0 0 0 2.75-2.75" /><path fill="currentColor" d="M15.25 8.25A2.75 2.75 0 0 0 12.5 5.5H7V4h5.5a4.25 4.25 0 0 1 0 8.5H7V11h5.5a2.75 2.75 0 0 0 2.75-2.75" /><path fill="currentColor" d="M6 4.5a.5.5 0 0 1 .5-.5h1v15.5h-1A.5.5 0 0 1 6 19z" />
    </IconBase>
  )
}

IconBoldText.displayName = "IconBoldText"
