// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconchatwithAi(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="#F5F5F7" strokeWidth={1.5} d="M20 8.5v-3a.5.5 0 0 0-.5-.5h-15a.5.5 0 0 0-.5.5v13.898a.5.5 0 0 0 .83.376L8 17h2M20.986 16.262c-.682.407-1.552.98-2.149 1.576-.596.596-1.167 1.465-1.574 2.147-.408-.682-.979-1.551-1.575-2.147-.596-.597-1.466-1.169-2.149-1.576.682-.408 1.552-.978 2.149-1.574.596-.597 1.167-1.467 1.575-2.15.407.683.978 1.553 1.575 2.15.596.596 1.466 1.166 2.148 1.574Z" />
    </IconBase>
  )
}

IconchatwithAi.displayName = "IconchatwithAi"
