// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconFindReference(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M19.864 6.999a.5.5 0 0 1 .136.342V20.5a.5.5 0 0 1-.5.5H13v-1.5h5.5V7.736L15.462 4.5H7.5V8H6V3.5a.5.5 0 0 1 .5-.5h9.611z" /><path fill="currentColor" d="M8.06 13.761a2.25 2.25 0 1 1 4.448-.685 2.25 2.25 0 0 1-4.447.685m-1.482.229a3.75 3.75 0 1 0 7.413-1.142 3.75 3.75 0 0 0-7.413 1.142" /><path fill="currentColor" d="m3.97 19.374 1.128.989 3.584-4.093-1.128-.988z" />
    </IconBase>
  )
}

IconFindReference.displayName = "IconFindReference"
