// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconLighting(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M15.25 12a3.25 3.25 0 1 0-6.5 0 3.25 3.25 0 0 0 6.5 0m1.5 0a4.75 4.75 0 1 1-9.5 0 4.75 4.75 0 0 1 9.5 0M12.75 2.5h-1.5V5h1.5zM12.75 19h-1.5v2.5h1.5zM18.849 5.414l-1.06-1.06L16.02 6.12l1.06 1.06zM7.182 17.082l-1.06-1.06-1.768 1.767 1.06 1.06zM4.354 5.414l1.06-1.06L7.182 6.12l-1.06 1.06zM16.021 17.082l1.06-1.06 1.768 1.767-1.06 1.06zM21.5 12.75v-1.5H19v1.5zM5 12.75v-1.5H2.5v1.5z" />
    </IconBase>
  )
}

IconLighting.displayName = "IconLighting"
