// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSignal(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="#F5F5F7" d="M15 19.75v1.5H9v-1.5z" /><path fill="#F5F5F7" d="M12.75 11.5v9h-1.5v-9z" /><path fill="#F5F5F7" d="M12 3a9 9 0 0 1 5.996 15.709l-.867-1.24a7.5 7.5 0 1 0-10.259 0l-.867 1.24A9 9 0 0 1 12 3m0 4a5 5 0 0 1 3.673 8.39l-.89-1.27a3.5 3.5 0 1 0-5.567 0l-.89 1.27A5 5 0 0 1 12 7" />
    </IconBase>
  )
}

IconSignal.displayName = "IconSignal"
