// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconThreeView(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M19.25 7.938 12 3.86 4.75 7.938v8.123L12 20.139l7.25-4.078zm1.5 8.562a.75.75 0 0 1-.382.653l-8 4.5a.75.75 0 0 1-.736 0l-8-4.5a.75.75 0 0 1-.382-.653v-9c0-.27.146-.52.382-.653l8-4.5a.75.75 0 0 1 .736 0l8 4.5a.75.75 0 0 1 .382.653z" /><path fill="currentColor" d="M12.75 3v9h-1.5V3z" /><path fill="currentColor" d="m12.386 12.644-7.5 4.5-.772-1.288 7.5-4.5z" /><path fill="currentColor" d="m11.614 12.644 7.5 4.5.772-1.288-7.5-4.5z" />
    </IconBase>
  )
}

IconThreeView.displayName = "IconThreeView"
