// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconNotification(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M14.5 18a2.5 2.5 0 0 1-5 0H11a1 1 0 1 0 2 0z" /><mask id="a" fill="#fff"><path d="M12 4a5 5 0 0 1 5 5v7H7V9a5 5 0 0 1 5-5" /></mask><path fill="currentColor" d="M17 16v1.5h1.5V16zM7 16H5.5v1.5H7zm5-12v1.5A3.5 3.5 0 0 1 15.5 9h3A6.5 6.5 0 0 0 12 2.5zm5 5h-1.5v7h3V9zm0 7v-1.5H7v3h10zM7 16h1.5V9h-3v7zm0-7h1.5A3.5 3.5 0 0 1 12 5.5v-3A6.5 6.5 0 0 0 5.5 9z" mask="url(#a)" /><path fill="currentColor" d="M19 14.75v1.5H5v-1.5z" />
    </IconBase>
  )
}

IconNotification.displayName = "IconNotification"
