// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconPin(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" clipPath="url(#a)"><path d="M12.75 20.75h-1.5v-6h1.5z" /><path d="m8.741 10.364-.05.326-2.941 1.961V14h12.5v-1.349l-2.941-1.96-.05-.327-.903-5.864H9.644zM19.75 14.25c0 .69-.56 1.25-1.25 1.25h-13c-.69 0-1.25-.56-1.25-1.25v-1.732c0-.418.209-.809.557-1.04l2.502-1.67.884-5.748A1.25 1.25 0 0 1 9.43 3h5.142a1.25 1.25 0 0 1 1.213.947l.023.113.883 5.749 2.503 1.668c.348.232.557.623.557 1.04z" /></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h24v24H0z" /></clipPath></defs>
    </IconBase>
  )
}

IconPin.displayName = "IconPin"
