// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function Icondefault(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <mask id="a" fill="#fff"><rect width={14} height={14} x={5} y={5} rx={0.5} /></mask><rect width={14} height={14} x={5} y={5} stroke="#F5F5F7" strokeWidth={3} mask="url(#a)" rx={0.5} />
    </IconBase>
  )
}

Icondefault.displayName = "Icondefault"
