// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconAlignLeft(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M4.75 4v16h-1.5V4z" /><mask id="a" fill="#fff"><rect width={13} height={5} x={7} y={6} rx={0.5} /></mask><rect width={13} height={5} x={7} y={6} stroke="currentColor" strokeWidth={3} mask="url(#a)" rx={0.5} /><mask id="b" fill="#fff"><rect width={10} height={5} x={7} y={13} rx={0.5} /></mask><rect width={10} height={5} x={7} y={13} stroke="currentColor" strokeWidth={3} mask="url(#b)" rx={0.5} />
    </IconBase>
  )
}

IconAlignLeft.displayName = "IconAlignLeft"
