// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSearch(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M8.85 7.16a5.5 5.5 0 1 1 .31 7.773l-1.017 1.102A7 7 0 1 0 17.64 5.748a7 7 0 0 0-9.497 10.287l1.018-1.102a5.5 5.5 0 0 1-.31-7.772" /><path fill="currentColor" d="m8.243 15 1.06 1.06-4.242 4.243L4 19.243z" />
    </IconBase>
  )
}

IconSearch.displayName = "IconSearch"
