// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function Iconplay(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M18.25 11.567a.5.5 0 0 1 0 .866l-12 6.928a.5.5 0 0 1-.75-.433H6l-.5-.866V5.073l.005-.071a.5.5 0 0 1 .745-.362zM5.5 18.927v-.864l.5.865zM7 6.805v10.392L16 12z" />
    </IconBase>
  )
}

Iconplay.displayName = "Iconplay"
