// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSettings(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="#F5F5F7" d="M16.208 3.25c.395 0 .763.187.997.497l.092.14 4.219 7.5c.214.38.214.846 0 1.226l-4.22 7.5a1.25 1.25 0 0 1-1.088.637H7.793a1.25 1.25 0 0 1-1.09-.637l-4.219-7.5a1.25 1.25 0 0 1 0-1.226l4.22-7.5.09-.14a1.25 1.25 0 0 1 .999-.497zM3.86 12l4.08 7.25h8.121L20.14 12 16.06 4.75H7.94z" /><path fill="#F5F5F7" d="M13.75 12a1.75 1.75 0 1 0-3.5 0 1.75 1.75 0 0 0 3.5 0m1.5 0a3.25 3.25 0 1 1-6.5 0 3.25 3.25 0 0 1 6.5 0" />
    </IconBase>
  )
}

IconSettings.displayName = "IconSettings"
