// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconGuide(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M19.5 12a7.5 7.5 0 1 0-7.5 7.5V21a9 9 0 1 1 0-18 9 9 0 0 1 0 18v-1.5a7.5 7.5 0 0 0 7.5-7.5" /><path stroke="currentColor" strokeLinecap="square" strokeLinejoin="round" strokeWidth={1.5} d="M12 13.5c0-1.765 2.5-2.117 2.5-4.065C14.5 7.82 13.5 7 12 7S9.5 8 9.5 9.252" /><path fill="currentColor" fillRule="evenodd" d="M12 17a1 1 0 1 0 0-2 1 1 0 0 0 0 2" clipRule="evenodd" />
    </IconBase>
  )
}

IconGuide.displayName = "IconGuide"
