// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconVolumeAdjustment(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M4.4 15.99a.5.5 0 0 1-.4-.49v-7a.5.5 0 0 1 .5-.5h3.033l.07-.005a.5.5 0 0 0 .135-.039l.062-.033 5.432-3.437a.5.5 0 0 1 .768.422v14.184a.5.5 0 0 1-.704.457l-.064-.034L7.8 16.077a.5.5 0 0 0-.196-.072L7.534 16v-1.5a2 2 0 0 1 .945.239l.124.07 3.897 2.467V6.724L8.603 9.19a2 2 0 0 1-1.07.31H5.5v5h2.033V16H4.5zM16 7c2.282.473 4 2.533 4 5.001S18.282 16.527 16 17v-1.577c1.445-.44 2.5-1.805 2.5-3.422S17.446 9.015 16 8.576z" />
    </IconBase>
  )
}

IconVolumeAdjustment.displayName = "IconVolumeAdjustment"
