// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconMarqueeSelect(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20 8h-1.5V5.5H16V4h4zM20 14h-1.5v2.5H16V18h4zM6.5 4a.5.5 0 0 0-.5.5V8h1.5V5.5H10V4zM12.976 9.11c.816-.327 1.626.483 1.3 1.299l-3.8 9.499c-.322.804-1.418.83-1.805.112l-.068-.154L7.285 16.1l-3.767-1.318-.153-.067c-.719-.387-.692-1.483.112-1.805zm-7.703 4.696 3.19 1.116 1.116 3.19 2.87-7.177z" />
    </IconBase>
  )
}

IconMarqueeSelect.displayName = "IconMarqueeSelect"
