// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconImageAssets(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M9 6v9h9V6zM8 16.5l-.1-.01a.5.5 0 0 1-.4-.49V5a.5.5 0 0 1 .5-.5h11a.5.5 0 0 1 .5.5v11a.5.5 0 0 1-.5.5z" /><path fill="currentColor" d="M5.5 18.5H14v1a.5.5 0 0 1-.5.5h-9l-.1-.01a.5.5 0 0 1-.4-.49v-8a.5.5 0 0 1 .5-.5h1zM16.03 10.97l-1.06 1.06-1.47-1.47-1.47 1.47-1.06-1.06 2.53-2.53z" />
    </IconBase>
  )
}

IconImageAssets.displayName = "IconImageAssets"
