// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function Iconadjustment(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M5 19h14v-5H5zm15.5 1a.5.5 0 0 1-.5.5H4a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5h16a.5.5 0 0 1 .5.5z" /><path fill="currentColor" d="M10 19V5H5v14zm1-15.5a.5.5 0 0 1 .5.5v16a.5.5 0 0 1-.5.5H4a.5.5 0 0 1-.5-.5V4a.5.5 0 0 1 .5-.5z" /><path fill="currentColor" d="M15 19V9H5v10zm1-11.5.1.01c.196.04.35.194.39.39l.01.1v12a.5.5 0 0 1-.5.5H4a.5.5 0 0 1-.49-.4L3.5 20V8l.01-.1A.5.5 0 0 1 4 7.5z" />
    </IconBase>
  )
}

Iconadjustment.displayName = "Iconadjustment"
