// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconGeometry2(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="currentColor" strokeWidth={1.5} d="M16.25 6.424v4.151L12 13.124l-4.25-2.549V6.424L12 3.875zM12 13.174v4.151l-4.25 2.549-4.25-2.549v-4.151l4.25-2.549zM20.5 13.174v4.151l-4.25 2.549L12 17.325v-4.151l4.25-2.549z" />
    </IconBase>
  )
}

IconGeometry2.displayName = "IconGeometry2"
