// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSmart(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M19.042 13.553a16 16 0 0 0-5.489 5.489L11.9 21.799l-1.653-2.757a16 16 0 0 0-5.489-5.489L2 11.9l2.757-1.653a16 16 0 0 0 5.228-5.07l.26-.419L11.9 2l1.653 2.757a16 16 0 0 0 5.07 5.228l.419.26 2.757 1.655zm-.772-2.022a17.5 17.5 0 0 1-6.002-6.002l-.369-.614-.368.614a17.5 17.5 0 0 1-6.002 6.002l-.613.368.613.369a17.5 17.5 0 0 1 6.002 6.002l.368.612.369-.612a17.5 17.5 0 0 1 6.002-6.002l.613-.37z" /><path fill="currentColor" d="m11.968 10.2 1.768 1.768-1.768 1.768-1.768-1.768z" />
    </IconBase>
  )
}

IconSmart.displayName = "IconSmart"
