// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconAlignTop(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20 4.75H4v-1.5h16zM7.5 8.5v10h2v-10zM6.5 20a.5.5 0 0 1-.5-.5v-12a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v12a.5.5 0 0 1-.5.5zM14.5 8.5v7h2v-7zm-1 8.5-.1-.01a.5.5 0 0 1-.39-.39l-.01-.1v-9l.01-.1a.5.5 0 0 1 .39-.39l.1-.01h4a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5z" />
    </IconBase>
  )
}

IconAlignTop.displayName = "IconAlignTop"
