// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconVersionUpdate(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20 7.5a.5.5 0 0 1 .5.5v11.5l-.01.1a.5.5 0 0 1-.39.39L20 20H4a.5.5 0 0 1-.5-.5V8a.5.5 0 0 1 .5-.5zm-15 11h14V9H5z" /><path fill="currentColor" d="M12.743 11.288V16h-1.5v-4.712z" /><path fill="currentColor" d="m15.235 13.823-1.06 1.061-2.182-2.182-2.182 2.182-1.061-1.06 3.243-3.243z" /><rect width={12} height={1.5} x={6} y={4} fill="currentColor" rx={0.5} />
    </IconBase>
  )
}

IconVersionUpdate.displayName = "IconVersionUpdate"
