// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconAddCamera(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="currentColor" strokeWidth={1.5} d="M15.25 6.75v10.5H3.75V6.75zM9.5 9.5v5M12 12H7M15.57 12.407a.5.5 0 0 1 0-.814l4.89-3.492a.5.5 0 0 1 .79.406v6.986a.5.5 0 0 1-.79.406z" />
    </IconBase>
  )
}

IconAddCamera.displayName = "IconAddCamera"
