// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconGeometry3(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M7 6.283a.5.5 0 0 1 .243-.429l4.5-2.7a.5.5 0 0 1 .514 0l4.5 2.7a.5.5 0 0 1 .243.43v4.433a.5.5 0 0 1-.243.429l-4.5 2.7a.5.5 0 0 1-.514 0l-4.5-2.7a.5.5 0 0 1-.243-.43z" /><path fill="currentColor" d="M2.75 13.033a.5.5 0 0 1 .243-.429l4.5-2.7a.5.5 0 0 1 .514 0l4.5 2.7a.5.5 0 0 1 .243.43v4.433a.5.5 0 0 1-.243.429l-4.5 2.7a.5.5 0 0 1-.514 0l-4.5-2.7a.5.5 0 0 1-.243-.43z" /><path fill="currentColor" d="M11.25 13.033a.5.5 0 0 1 .243-.429l4.5-2.7a.5.5 0 0 1 .514 0l4.5 2.7a.5.5 0 0 1 .243.43v4.433a.5.5 0 0 1-.243.429l-4.5 2.7a.5.5 0 0 1-.514 0l-4.5-2.7a.5.5 0 0 1-.243-.43z" />
    </IconBase>
  )
}

IconGeometry3.displayName = "IconGeometry3"
