// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconModel3D(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M19.5 12a7.5 7.5 0 1 0-7.5 7.5V21a9 9 0 1 1 0-18 9 9 0 0 1 0 18v-1.5a7.5 7.5 0 0 0 7.5-7.5" /><path fill="currentColor" d="M20 11.25v1.5H4v-1.5z" /><path fill="currentColor" d="M9.516 11.25q-.015.369-.016.75c0 2.326.422 4.36 1.042 5.755.311.7.643 1.173.935 1.451.285.27.459.294.523.294s.238-.023.523-.294c.292-.278.624-.751.935-1.451.41-.923.732-2.125.904-3.505h1.512C15.43 18.132 13.864 21 12 21c-2.21 0-4-4.03-4-9q0-.38.015-.75zM12 3c2.21 0 4 4.03 4 9q0 .38-.015.75h-1.5q.015-.369.015-.75c0-2.326-.422-4.36-1.042-5.755-.311-.7-.643-1.173-.935-1.451-.285-.27-.459-.294-.523-.294s-.238.023-.523.294c-.292.278-.624.751-.935 1.451-.41.923-.732 2.125-.904 3.505H8.126C8.57 5.868 10.136 3 12 3" />
    </IconBase>
  )
}

IconModel3D.displayName = "IconModel3D"
