// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconObjectScaling(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M19.5 4a.5.5 0 0 1 .5.5v15a.5.5 0 0 1-.4.49l-.1.01H15v-1.5h3.5v-13h-13V9H4V4.5a.5.5 0 0 1 .5-.5z" /><path fill="currentColor" d="M14.5 9a.5.5 0 0 1 .5.5V14h-1.5v-3a.5.5 0 0 0-.5-.5h-3V9zM5.5 18.5h4v-4h-4zm5.5 1-.01.1a.5.5 0 0 1-.39.39l-.1.01h-6a.5.5 0 0 1-.49-.4L4 19.5v-6a.5.5 0 0 1 .5-.5h6l.1.01a.5.5 0 0 1 .4.49z" /><path fill="currentColor" d="m14.53 10.53-4 4-1.06-1.06 4-4z" />
    </IconBase>
  )
}

IconObjectScaling.displayName = "IconObjectScaling"
