// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconCanvasMode(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M5.5 8.5h3v-3h-3zm4.5 1a.5.5 0 0 1-.5.5h-5l-.1-.01A.5.5 0 0 1 4 9.5v-5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 .5.5zM15.5 18.5h3v-3h-3zm4.5 1a.5.5 0 0 1-.5.5h-5l-.1-.01a.5.5 0 0 1-.4-.49v-5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 .5.5z" /><path fill="currentColor" d="M5.25 14.6a3.15 3.15 0 0 1 3.15-3.15h7a1.85 1.85 0 0 0 0-3.7H9.777v-1.5H15.4a3.35 3.35 0 0 1 0 6.7h-7a1.65 1.65 0 1 0 0 3.3h5.823v1.5H8.4a3.15 3.15 0 0 1-3.15-3.15" />
    </IconBase>
  )
}

IconCanvasMode.displayName = "IconCanvasMode"
