// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconText(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="#F5F5F7" strokeWidth={1.5} d="M9.214 3.75 5.75 7.44v12.81h12.5V3.75z" /><path fill="#F5F5F7" d="M15 10.25v1.5H9v-1.5zM15 14.25v1.5H9v-1.5z" />
    </IconBase>
  )
}

IconText.displayName = "IconText"
