// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function Iconscore(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="#F5F5F7" strokeLinejoin="round" strokeWidth={1.35} d="M12 3.45 9.248 9.065 3 9.97l4.527 4.425-1.083 6.154L12 17.589l5.556 2.961-1.074-6.154L21 9.971l-6.214-.906z" />
    </IconBase>
  )
}

Iconscore.displayName = "Iconscore"
