// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconPause(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M5.5 18.5h13v-13h-13zm14.5 1a.5.5 0 0 1-.4.49l-.1.01h-15l-.1-.01a.5.5 0 0 1-.39-.39L4 19.5v-15a.5.5 0 0 1 .5-.5h15a.5.5 0 0 1 .5.5z" />
    </IconBase>
  )
}

IconPause.displayName = "IconPause"
