// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconChatWithAI(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20.75 7.5h-1.5V5.75H4.75v13.097l2.968-2.597H9v1.5h-.718l-2.959 2.589c-.808.707-2.073.133-2.073-.94V5.5c0-.69.56-1.25 1.25-1.25h15c.69 0 1.25.56 1.25 1.25z" /><path stroke="currentColor" strokeWidth={1.5} d="M22.104 15.13c-.859.502-2.036 1.252-2.814 2.029-.777.777-1.526 1.954-2.027 2.813-.501-.859-1.25-2.036-2.028-2.813-.777-.777-1.955-1.527-2.813-2.028.858-.501 2.036-1.25 2.813-2.027s1.527-1.956 2.028-2.814c.5.858 1.25 2.037 2.027 2.814s1.956 1.526 2.814 2.027Z" />
    </IconBase>
  )
}

IconChatWithAI.displayName = "IconChatWithAI"
