// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconUnGroup(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M4 8h1.5V5.5H8V4H4zM4 16h1.5v2.5H8V20H4zM19.5 4a.5.5 0 0 1 .5.5V8h-1.5V5.5H16V4zM20 16h-1.5v2.5H16V20h4z" /><path fill="currentColor" d="M18.5 9.5h-4v-4h4zm-5.5 1 .01.1c.04.196.194.35.39.39l.1.01h6a.5.5 0 0 0 .49-.4l.01-.1v-6a.5.5 0 0 0-.5-.5h-6l-.1.01a.5.5 0 0 0-.4.49zM9.5 18.5h-4v-4h4zm-5.5 1 .01.1c.04.196.194.35.39.39l.1.01h6a.5.5 0 0 0 .49-.4l.01-.1v-6a.5.5 0 0 0-.5-.5h-6l-.1.01a.5.5 0 0 0-.4.49z" />
    </IconBase>
  )
}

IconUnGroup.displayName = "IconUnGroup"
