// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconCircle(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M18 12a6 6 0 1 0-6 6v1.5a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15V18a6 6 0 0 0 6-6" />
    </IconBase>
  )
}

IconCircle.displayName = "IconCircle"
