// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconDefaultAvatar(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <circle cx={12} cy={9} r={4.25} stroke="currentColor" strokeWidth={1.5} /><path fill="currentColor" d="M14 16a6 6 0 0 1 5.915 5h-1.528A4.5 4.5 0 0 0 14 17.5h-4A4.5 4.5 0 0 0 5.613 21H4.085A6 6 0 0 1 10 16z" />
    </IconBase>
  )
}

IconDefaultAvatar.displayName = "IconDefaultAvatar"
