// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconEdit(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="#F5F5F7" d="M21.5 19.25v1.5h-18v-1.5zM15.934 2.25c.199 0 .39.08.53.22l3.652 3.654a.75.75 0 0 1 0 1.06l-8.926 8.932a.75.75 0 0 1-.532.22H7a.75.75 0 0 1-.75-.75v-3.64a.75.75 0 0 1 .22-.53l8.932-8.946.115-.094a.75.75 0 0 1 .417-.126M7.75 12.255v2.58h2.598l8.177-8.182-2.591-2.592z" />
    </IconBase>
  )
}

IconEdit.displayName = "IconEdit"
