// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconMaximizePreview(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="m19.53 5.53-5 5-1.06-1.06 5-5zM19.53 18.47l-5-5-1.06 1.06 5 5zM4.47 5.53l5 5 1.06-1.06-5-5zM4.47 18.47l5-5 1.06 1.06-5 5z" /><path fill="currentColor" d="M19.5 4a.5.5 0 0 1 .5.5V9h-1.5V6a.5.5 0 0 0-.5-.5h-3V4zM19.5 20a.5.5 0 0 0 .5-.5V15h-1.5v3.5H15V20zM4.5 4a.5.5 0 0 0-.5.5V9h1.5V5.5H9V4zM4.5 20a.5.5 0 0 1-.5-.5V15h1.5v3.5H9V20z" />
    </IconBase>
  )
}

IconMaximizePreview.displayName = "IconMaximizePreview"
