// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconDownload(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="#F5F5F7" d="m11.25 13.001-.021-10 1.499-.003.022 10z" /><path fill="#F5F5F7" d="m8.15 10.829 1.06-1.061 2.768 2.768 2.768-2.768 1.06 1.06-3.828 3.829z" /><path fill="#F5F5F7" d="M19.75 19.5c0 .69-.56 1.25-1.25 1.25h-13c-.69 0-1.25-.56-1.25-1.25V11h1.5v8.25h12.5V11h1.5z" />
    </IconBase>
  )
}

IconDownload.displayName = "IconDownload"
