// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconImageEdite(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20.5 4a.5.5 0 0 1 .5.5v15a.5.5 0 0 1-.5.5h-17a.5.5 0 0 1-.5-.5v-15a.5.5 0 0 1 .5-.5zm-16 14.5h15v-13h-15z" /><path fill="currentColor" d="M16 13.5V15h-3v-1.5zM9.768 14.718l-1.238.176.177-1.237L14.364 8l1.06 1.06z" />
    </IconBase>
  )
}

IconImageEdite.displayName = "IconImageEdite"
