// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconCharacters(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M14.75 7.25a2.75 2.75 0 1 0-5.5 0 2.75 2.75 0 0 0 5.5 0m1.5 0a4.25 4.25 0 1 1-8.5 0 4.25 4.25 0 0 1 8.5 0M16.25 3.76a3.5 3.5 0 0 1 0 6.98c.375-.457.677-.975.89-1.537a2.26 2.26 0 0 0 0-3.907 5.5 5.5 0 0 0-.89-1.536M7.75 3.76a3.5 3.5 0 0 0 0 6.98 5.5 5.5 0 0 1-.89-1.537 2.26 2.26 0 0 1 0-3.907c.213-.562.515-1.08.89-1.536M17 17a2.5 2.5 0 0 0-2.5-2.5h-5A2.5 2.5 0 0 0 7 17v1.5h10zm1.5 2.5-.01.1a.5.5 0 0 1-.39.39L18 20H6a.5.5 0 0 1-.49-.4l-.01-.1V17a4 4 0 0 1 4-4h5l.206.005A4 4 0 0 1 18.5 17zM18.5 13.065A4 4 0 0 1 21.782 17v2.5l-.01.1a.5.5 0 0 1-.39.39l-.1.01h-1l-.005-1.5h.005V17q0-.105-.01-.206v-.012c0-1.588-.662-2.977-1.772-3.717M5.502 13a4 4 0 0 0-3.282 3.936v2.5l.01.1c.04.196.194.35.39.39l.1.01h1l.005-1.5H3.72v-1.5q0-.105.01-.206v-.012c0-1.589.662-2.977 1.772-3.718" />
    </IconBase>
  )
}

IconCharacters.displayName = "IconCharacters"
