// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconProject(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <rect width={5.5} height={5.5} x={13.75} y={4.75} stroke="currentColor" strokeWidth={1.5} rx={2.75} /><mask id="a" fill="#fff"><rect width={7} height={7} x={4} y={4} rx={0.5} /></mask><rect width={7} height={7} x={4} y={4} stroke="currentColor" strokeWidth={3} mask="url(#a)" rx={0.5} /><mask id="b" fill="#fff"><rect width={7} height={7} x={13} y={13} rx={0.5} /></mask><rect width={7} height={7} x={13} y={13} stroke="currentColor" strokeWidth={3} mask="url(#b)" rx={0.5} /><mask id="c" fill="#fff"><rect width={7} height={7} x={4} y={13} rx={0.5} /></mask><rect width={7} height={7} x={4} y={13} stroke="currentColor" strokeWidth={3} mask="url(#c)" rx={0.5} />
    </IconBase>
  )
}

IconProject.displayName = "IconProject"
