// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconVideoCamera(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M5.5 18.5h9v-5h-9zm10.5 1a.5.5 0 0 1-.4.49l-.1.01h-11a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5h11l.1.01a.5.5 0 0 1 .4.49z" /><path fill="currentColor" d="M15.174 16.685a.95.95 0 0 1 .09-1.445l3.626-2.72a.85.85 0 0 1 1.36.68v5.6c0 .7-.8 1.1-1.36.68l-3.626-2.72zm3.576.815v-3l-2 1.5zM8.423 7.676a1.5 1.5 0 1 0-1.06 1.837l.388 1.45a3 3 0 1 1-1.553-5.797 3 3 0 0 1 1.553 5.796l-.389-1.449a1.5 1.5 0 0 0 1.061-1.837" /><path fill="currentColor" d="M15.54 6.08a2.783 2.783 0 1 0-1.968 3.409l.388 1.448a4.283 4.283 0 1 1-2.217-8.274 4.283 4.283 0 0 1 2.217 8.275l-.388-1.45A2.783 2.783 0 0 0 15.54 6.08" />
    </IconBase>
  )
}

IconVideoCamera.displayName = "IconVideoCamera"
