// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconAddTag(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" clipPath="url(#a)"><path d="M12.708 5.142 5.12 12.728l6.364 6.364 7.587-7.586-.49-5.875zm-.87 15.718-.077.064a.5.5 0 0 1-.551 0l-.078-.064-7.778-7.778a.5.5 0 0 1 0-.708l8.62-8.62a.5.5 0 0 1 .395-.145l7.18.598a.5.5 0 0 1 .457.458l.599 7.179a.5.5 0 0 1-.146.395z" /><path d="m13.914 9 1.414 1.414-1.414 1.414-1.414-1.414z" /></g><defs><clipPath id="a"><path fill="currentColor" d="M24 0H0v24h24z" /></clipPath></defs>
    </IconBase>
  )
}

IconAddTag.displayName = "IconAddTag"
