// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSkills(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="currentColor" strokeWidth={1.5} d="M7.184 4.75a5.25 5.25 0 0 1 2.912.882L12 6.902l1.904-1.27a5.25 5.25 0 0 1 2.912-.882h2.434v12.5h-2.434a6.75 6.75 0 0 0-3.744 1.134L12 19.099l-1.072-.715a6.75 6.75 0 0 0-3.744-1.134H4.75V4.75z" /><path fill="currentColor" d="M12.75 7v12h-1.5V7z" />
    </IconBase>
  )
}

IconSkills.displayName = "IconSkills"
