// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconLocation(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M14 20v-1.44h4.56V14H20v4.8a1.2 1.2 0 0 1-1.2 1.2zM14 4v1.44h4.56V10H20V5.2A1.2 1.2 0 0 0 18.8 4zM10 4v1.44H5.44V10H4V5.2A1.2 1.2 0 0 1 5.2 4zM10 20v-1.44H5.44V14H4v4.8A1.2 1.2 0 0 0 5.2 20zM11.914 10.5l1.414 1.414-1.414 1.414-1.414-1.414z" />
    </IconBase>
  )
}

IconLocation.displayName = "IconLocation"
