// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconDefaultAssets(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M4.5 18h15V9.284L15.467 6H4.5zM21 19l-.01.1a.5.5 0 0 1-.49.4h-17A.5.5 0 0 1 3 19V5a.5.5 0 0 1 .5-.5H16l4.815 3.92a.5.5 0 0 1 .185.39z" /><path fill="currentColor" d="M9.5 13.5h3v-3h-3zm4.5-2.167 1.69-1.126a.2.2 0 0 1 .31.167v3.252a.2.2 0 0 1-.31.167L14 12.666V14.5a.5.5 0 0 1-.5.5h-5a.5.5 0 0 1-.5-.5v-5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 .5.5z" />
    </IconBase>
  )
}

IconDefaultAssets.displayName = "IconDefaultAssets"
