// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconAuthorization(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M12.75 3v4h-1.5V3zM21 12.75h-4v-1.5h4zM17.728 18.789l-2.829-2.829 1.061-1.06 2.829 2.828zM6.06 18.789l2.83-2.829-1.062-1.06L5 17.728zM12.75 17v4h-1.5v-4zM7 12.75H3v-1.5h4zM7.828 8.89 5 6.06 6.06 5l2.83 2.828zM15.96 8.89l2.829-2.83L17.728 5l-2.829 2.828zM13.25 12a1.25 1.25 0 1 0-2.5 0 1.25 1.25 0 0 0 2.5 0m1.5 0a2.75 2.75 0 1 1-5.5 0 2.75 2.75 0 0 1 5.5 0" />
    </IconBase>
  )
}

IconAuthorization.displayName = "IconAuthorization"
