// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconModel3D(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20 3.25a.75.75 0 0 1 .75.75v10a.75.75 0 0 1-.174.48l-5 6a.75.75 0 0 1-.576.27H4a.75.75 0 0 1-.75-.75V10a.75.75 0 0 1 .174-.48l5-6 .056-.061A.75.75 0 0 1 9 3.25zM4.75 10.272v8.978h9.898l4.602-5.523V4.75H9.352z" /><path fill="currentColor" d="M14.25 19.5V10a.75.75 0 0 1 1.5 0v9.5a.75.75 0 0 1-1.5 0" /><path fill="currentColor" d="M15 9.25a.75.75 0 0 1 0 1.5H4a.75.75 0 0 1 0-1.5z" /><path fill="currentColor" d="M19.424 3.52a.75.75 0 0 1 1.152.96l-5 6a.75.75 0 0 1-1.152-.96z" />
    </IconBase>
  )
}

IconModel3D.displayName = "IconModel3D"
