// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconAppendix(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="#F5F5F7" strokeWidth={1.5} d="M6 8v6.25a5.75 5.75 0 0 0 11.5 0V7.923a3.923 3.923 0 1 0-7.846 0v5.886a2.077 2.077 0 0 0 4.154 0V8" />
    </IconBase>
  )
}

IconAppendix.displayName = "IconAppendix"
