// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function Iconadjustment(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <mask id="a" fill="#fff"><rect width={17} height={8} x={3.5} y={12.5} rx={0.5} /></mask><rect width={17} height={8} x={3.5} y={12.5} stroke="#F5F5F7" strokeWidth={3} mask="url(#a)" rx={0.5} /><mask id="b" fill="#fff"><rect width={17} height={8} x={3.5} y={20.5} rx={0.5} transform="rotate(-90 3.5 20.5)" /></mask><rect width={17} height={8} x={3.5} y={20.5} stroke="#F5F5F7" strokeWidth={3} mask="url(#b)" rx={0.5} transform="rotate(-90 3.5 20.5)" /><mask id="c" fill="#fff"><rect width={13} height={13} x={3.5} y={20.5} rx={0.5} transform="rotate(-90 3.5 20.5)" /></mask><rect width={13} height={13} x={3.5} y={20.5} stroke="#F5F5F7" strokeWidth={3} mask="url(#c)" rx={0.5} transform="rotate(-90 3.5 20.5)" />
    </IconBase>
  )
}

Iconadjustment.displayName = "Iconadjustment"
