// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconChatWithAI(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20.75 8.5h-1.5V5.75H4.75v13.097l2.968-2.597H10v1.5H8.282l-2.959 2.589c-.808.707-2.073.133-2.073-.94V5.5c0-.69.56-1.25 1.25-1.25h15c.69 0 1.25.56 1.25 1.25z" /><path stroke="#F5F5F7" strokeWidth={1.5} d="M20.986 16.262c-.682.407-1.552.98-2.149 1.576-.596.596-1.167 1.465-1.574 2.147-.408-.682-.979-1.551-1.575-2.147-.596-.597-1.466-1.169-2.149-1.576.682-.408 1.552-.978 2.149-1.574.596-.597 1.167-1.467 1.575-2.15.407.683.978 1.553 1.575 2.15.596.596 1.466 1.166 2.148 1.574Z" />
    </IconBase>
  )
}

IconChatWithAI.displayName = "IconChatWithAI"
