// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconState(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M17.537 3.547 7.647 20.38l-1.294-.76 9.89-16.833zM7.678 8l-3.11 4 1.795 2.309-.817 1.392-2.283-2.933-.061-.087a1.25 1.25 0 0 1 0-1.362l.061-.087L5.778 8zM20.415 11.232l.062.087a1.25 1.25 0 0 1 0 1.362l-.062.087L17.9 16H16l3.111-4-1.913-2.459.818-1.393z" />
    </IconBase>
  )
}

IconState.displayName = "IconState"
