// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconMap(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="currentColor" strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M19.25 7.445v11.291l-4.14-2.258a1.25 1.25 0 0 0-1.094-.05l-.147.076-4.387 2.632-4.732-2.582V5.263L8.89 7.52a1.25 1.25 0 0 0 1.24-.025l4.387-2.633zM9.5 8v10.5M14.5 5v11" />
    </IconBase>
  )
}

IconMap.displayName = "IconMap"
