// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconVideoClip(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <circle cx={16.281} cy={18.039} r={2.75} stroke="currentColor" strokeWidth={1.5} transform="rotate(-30 16.281 18.04)" /><path fill="currentColor" d="m8.68 3.375 7 12.124-1.298.75-7-12.124z" /><circle cx={3.5} cy={3.5} r={2.75} stroke="currentColor" strokeWidth={1.5} transform="scale(-1 1)rotate(-30 24.99 31.82)" /><path fill="currentColor" d="m15.382 3.375-7 12.124 1.299.75 7-12.124z" />
    </IconBase>
  )
}

IconVideoClip.displayName = "IconVideoClip"
