// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconAz8Logo(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <rect width={18} height={18} x={3} y={3} rx={4} /><path d="m8 16 4-9 4 9M9.5 13h5" />
    </IconBase>
  )
}

IconAz8Logo.displayName = "IconAz8Logo"
