// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconLike(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M19.65 8.845c0-1.946-1.612-3.524-3.6-3.524-1.216 0-2.292.59-2.946 1.498A1.36 1.36 0 0 1 12 7.38c-.44 0-.851-.21-1.104-.56A3.62 3.62 0 0 0 7.95 5.32c-1.988 0-3.6 1.578-3.6 3.524s1.208 4.172 2.98 6.134c1.582 1.751 3.398 3.052 4.67 3.602 1.272-.55 3.088-1.85 4.67-3.601 1.772-1.963 2.98-4.19 2.98-6.135m1.35 0c0 4.845-5.85 10.13-9 11.155-3.15-1.025-9-6.31-9-11.155C3 6.169 5.216 4 7.95 4c1.674 0 3.154.813 4.05 2.059A4.98 4.98 0 0 1 16.05 4C18.784 4 21 6.17 21 8.845" />
    </IconBase>
  )
}

IconLike.displayName = "IconLike"
