// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconExtendDuration(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M4.5 18h15V9.284L15.467 6H4.5zM21 19l-.01.1a.5.5 0 0 1-.49.4h-17A.5.5 0 0 1 3 19V5a.5.5 0 0 1 .5-.5H16l4.815 3.92a.5.5 0 0 1 .185.39z" /><path fill="currentColor" d="m13.743 15.486-1.06-1.061 2.181-2.182-2.182-2.182L13.742 9l3.243 3.243zM9.243 15.486l-1.06-1.061 2.181-2.182-2.182-2.182L9.242 9l3.243 3.243z" />
    </IconBase>
  )
}

IconExtendDuration.displayName = "IconExtendDuration"
