// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconDropDownArrow(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="m18.53 9.53-5.646 6.647a1.25 1.25 0 0 1-1.768 0L5.47 9.53l1.06-1.06L12 14.94l5.47-6.47z" />
    </IconBase>
  )
}

IconDropDownArrow.displayName = "IconDropDownArrow"
