// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconLike(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20.5 8.5a4 4 0 0 0-7.273-2.3 1.5 1.5 0 0 1-2.454 0A4 4 0 0 0 3.5 8.5c0 2.208 1.342 4.736 3.312 6.964 1.757 1.987 3.774 3.464 5.188 4.089 1.414-.625 3.431-2.102 5.189-4.09C19.158 13.237 20.5 10.709 20.5 8.5m1.5 0C22 14 15.5 20 12 21.163 8.5 20 2 14 2 8.5a5.5 5.5 0 0 1 10-3.163A5.5 5.5 0 0 1 22 8.5" />
    </IconBase>
  )
}

IconLike.displayName = "IconLike"
