// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconAlignLeft(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M4.75 4v16h-1.5V4zM8.5 9.5h10v-2h-10zm11.5 1a.5.5 0 0 1-.5.5h-12a.5.5 0 0 1-.5-.5v-4a.5.5 0 0 1 .5-.5h12a.5.5 0 0 1 .5.5zM8.5 16.5h7v-2h-7zm8.5 1a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-4a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5z" />
    </IconBase>
  )
}

IconAlignLeft.displayName = "IconAlignLeft"
