// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconStoryboard(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M4.75 9.75h6v-4.5h-6zm7.5.25c0 .69-.56 1.25-1.25 1.25H4.5c-.69 0-1.25-.56-1.25-1.25V5c0-.69.56-1.25 1.25-1.25H11c.69 0 1.25.56 1.25 1.25zM13.25 18.75h6v-4.5h-6zm7.5.25c0 .69-.56 1.25-1.25 1.25H13c-.69 0-1.25-.56-1.25-1.25v-5c0-.69.56-1.25 1.25-1.25h6.5c.69 0 1.25.56 1.25 1.25zM15.25 9.75h4v-4.5h-4zm5.5.25c0 .69-.56 1.25-1.25 1.25H15c-.69 0-1.25-.56-1.25-1.25V5c0-.69.56-1.25 1.25-1.25h4.5c.69 0 1.25.56 1.25 1.25zM4.75 18.75h4v-4.5h-4zm5.5.25c0 .69-.56 1.25-1.25 1.25H4.5c-.69 0-1.25-.56-1.25-1.25v-5c0-.69.56-1.25 1.25-1.25H9c.69 0 1.25.56 1.25 1.25z" />
    </IconBase>
  )
}

IconStoryboard.displayName = "IconStoryboard"
