// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconRectangle(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M6.5 16.5h11v-9h-11zm12.5 1a.5.5 0 0 1-.4.49l-.1.01h-13l-.1-.01a.5.5 0 0 1-.39-.39L5 17.5v-11a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5z" />
    </IconBase>
  )
}

IconRectangle.displayName = "IconRectangle"
