// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconBodyText(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="m12.77 3.828-.15 15.522-1.5-.01.15-15.523z" /><path fill="currentColor" d="M18.75 7a.5.5 0 0 1-.5.5h-.5a.5.5 0 0 1-.5-.5V4.75H6.75V7a.5.5 0 0 1-.5.5h-.5a.5.5 0 0 1-.5-.5V4.5c0-.69.56-1.25 1.25-1.25h11c.69 0 1.25.56 1.25 1.25zM15.5 18.25a.5.5 0 0 1 .5.5v.5a.5.5 0 0 1-.5.5h-7a.5.5 0 0 1-.5-.5v-.5a.5.5 0 0 1 .5-.5z" />
    </IconBase>
  )
}

IconBodyText.displayName = "IconBodyText"
