// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconModel3D(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M19.5 12a7.5 7.5 0 1 0-7.5 7.5V21a9 9 0 1 1 0-18 9 9 0 0 1 0 18v-1.5a7.5 7.5 0 0 0 7.5-7.5" /><path fill="currentColor" d="M20 11.25v1.5H4v-1.5z" /><path fill="currentColor" d="M14.5 12c0-2.326-.422-4.36-1.042-5.755-.311-.7-.643-1.173-.935-1.451-.285-.27-.459-.294-.523-.294s-.238.023-.523.294c-.292.278-.624.751-.935 1.451C9.922 7.641 9.5 9.675 9.5 12c0 2.326.422 4.36 1.042 5.755.311.7.643 1.173.935 1.451.285.27.459.294.523.294V21c-2.21 0-4-4.03-4-9s1.79-9 4-9 4 4.03 4 9-1.79 9-4 9v-1.5c.064 0 .238-.023.523-.294.292-.278.624-.751.935-1.451.62-1.396 1.042-3.43 1.042-5.755" />
    </IconBase>
  )
}

IconModel3D.displayName = "IconModel3D"
