// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconTakePhoto(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M4.75 18.75h14.5V8.25H4.75zm16 .25c0 .69-.56 1.25-1.25 1.25h-15c-.69 0-1.25-.56-1.25-1.25V8c0-.69.56-1.25 1.25-1.25h15c.69 0 1.25.56 1.25 1.25z" /><circle cx={12} cy={13.5} r={3.25} stroke="currentColor" strokeWidth={1.5} /><path fill="currentColor" d="M8.5 4a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 .5.5v.5a.5.5 0 0 1-.5.5H9a.5.5 0 0 1-.5-.5z" />
    </IconBase>
  )
}

IconTakePhoto.displayName = "IconTakePhoto"
