// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconFilter(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M9.838 12.515a.75.75 0 0 1 .112.394v6.341h4.1v-6.34c0-.14.039-.277.112-.395l4.492-7.265H5.346zM15.55 19.5c0 .69-.56 1.25-1.25 1.25H9.7c-.69 0-1.25-.56-1.25-1.25v-6.378L3.834 5.657A1.25 1.25 0 0 1 4.897 3.75h14.206a1.25 1.25 0 0 1 1.063 1.907l-4.616 7.465z" />
    </IconBase>
  )
}

IconFilter.displayName = "IconFilter"
