// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconFail(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M12.754 13h-1.5l-.23-4.977a.5.5 0 0 1 .5-.523h.953a.5.5 0 0 1 .5.522z" /><path fill="currentColor" d="M5.5 19.5h13V7.736L15.462 4.5H5.5zm14.5 1a.5.5 0 0 1-.5.5h-15l-.1-.01a.5.5 0 0 1-.4-.49v-17a.5.5 0 0 1 .5-.5h11.611l3.753 3.999a.5.5 0 0 1 .136.342z" /><circle cx={12} cy={16} r={1} fill="currentColor" />
    </IconBase>
  )
}

IconFail.displayName = "IconFail"
