// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconShare(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="m20.06 4.998-8 9-1.12-.996 8-9z" /><path fill="currentColor" d="M10.5 5H5v14h14v-5.5h1.5V20l-.01.1a.5.5 0 0 1-.39.39l-.1.01H4a.5.5 0 0 1-.49-.4L3.5 20V4a.5.5 0 0 1 .5-.5h6.5zM20.5 9.5H19V5h-4.5V3.5h6z" />
    </IconBase>
  )
}

IconShare.displayName = "IconShare"
