// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconCommunity(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M12.25 7a2.75 2.75 0 1 0-5.5 0 2.75 2.75 0 0 0 5.5 0m1.5 0a4.25 4.25 0 1 1-8.5 0 4.25 4.25 0 0 1 8.5 0M15.5 3.5a3.5 3.5 0 1 1-.702 6.929q.428-.535.714-1.165a2.264 2.264 0 0 0 0-4.529 5.5 5.5 0 0 0-.714-1.165q.34-.07.702-.07M14.5 17a2.5 2.5 0 0 0-2.5-2.5H7A2.5 2.5 0 0 0 4.5 17v1.5h10zm1.5 2.5-.01.1a.5.5 0 0 1-.39.39l-.1.01h-12a.5.5 0 0 1-.49-.4L3 19.5V17a4 4 0 0 1 4-4h5l.206.005A4 4 0 0 1 16 17zM16.718 13.065A4 4 0 0 1 20 17v2.5l-.01.1a.5.5 0 0 1-.39.39l-.1.01h-1l-.005-1.5h.005V17q0-.105-.01-.206v-.012c0-1.588-.662-2.977-1.772-3.717" />
    </IconBase>
  )
}

IconCommunity.displayName = "IconCommunity"
