// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconCopyImage(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M9.5 3.75v1.5h9.75V15h1.5V5c0-.69-.56-1.25-1.25-1.25z" /><path fill="currentColor" d="M5.5 9v9h10V9zm-1 10.5-.1-.01A.5.5 0 0 1 4 19V8a.5.5 0 0 1 .5-.5h12a.5.5 0 0 1 .5.5v11a.5.5 0 0 1-.5.5z" /><path fill="currentColor" d="m13.172 14.534 2.453-1.416.75 1.299-3.547 2.048-2.482-2.979-4.944 3.147-.804-1.266 6.056-3.854z" />
    </IconBase>
  )
}

IconCopyImage.displayName = "IconCopyImage"
