// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconCollapseGroup(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20 4.25v1.5H4v-1.5zM12 14.394l8 6.223v-1.9l-7.232-5.627-.087-.061a1.25 1.25 0 0 0-1.362 0l-.087.061L4 18.716v1.9z" /><path fill="currentColor" d="m12 9.567 8 6.222v-1.9l-7.232-5.626-.087-.061a1.25 1.25 0 0 0-1.362 0l-.087.061L4 13.89v1.9z" />
    </IconBase>
  )
}

IconCollapseGroup.displayName = "IconCollapseGroup"
