// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconVideo(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M9.223 7.207a2.04 2.04 0 1 0-4.027.67 2.04 2.04 0 0 0 4.027-.67m1.48-.245A3.542 3.542 0 1 1 3.715 8.12a3.542 3.542 0 0 1 6.988-1.158" /><path fill="currentColor" d="M14.804 7.207a2.041 2.041 0 1 0-4.027.67 2.041 2.041 0 0 0 4.027-.67m1.48-.245A3.541 3.541 0 1 1 9.295 8.12a3.541 3.541 0 0 1 6.987-1.158M5.5 18.5h9v-5h-9zm10.5 1a.5.5 0 0 1-.4.49l-.1.01h-11a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5h11l.1.01a.5.5 0 0 1 .4.49z" /><path fill="currentColor" d="M15.174 16.685a.95.95 0 0 1 .09-1.445l3.626-2.72a.85.85 0 0 1 1.36.68v5.6c0 .7-.8 1.1-1.36.68l-3.626-2.72zm3.576.815v-3l-2 1.5z" />
    </IconBase>
  )
}

IconVideo.displayName = "IconVideo"
