// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconDefaultAssets(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M4.5 18h15V9.284L15.467 6H4.5zM21 19l-.01.1a.5.5 0 0 1-.49.4h-17A.5.5 0 0 1 3 19V5a.5.5 0 0 1 .5-.5H16l4.815 3.92a.5.5 0 0 1 .185.39z" /><mask id="a" fill="#fff"><path d="M13.5 9a.5.5 0 0 1 .5.5v1.833l1.69-1.126a.2.2 0 0 1 .31.167v3.252a.2.2 0 0 1-.31.167L14 12.666V14.5a.5.5 0 0 1-.5.5h-5a.5.5 0 0 1-.5-.5v-5a.5.5 0 0 1 .5-.5z" /></mask><path fill="currentColor" d="M14 9.5h1.2zm0 1.833h-1.2v2.242l1.865-1.243zm1.69-1.126-.664-1-.002.001zm.31.167h-1.2zm0 3.252h1.2zm-.31.167-.666.998.002.002zM14 12.666l.666-.998-1.866-1.245v2.243zM13.5 15v1.2zM8 14.5H6.8zM8.5 9V7.8zm5 0v1.2a.7.7 0 0 1-.7-.7h2.4a1.7 1.7 0 0 0-1.7-1.7zm.5.5h-1.2v1.833h2.4V9.5zm0 1.833.665.999 1.69-1.126-.665-.999-.666-.999-1.69 1.127zm1.69-1.126.663 1a1 1 0 0 1-1.553-.833h2.4c0-1.114-1.24-1.786-2.174-1.167zm.31.167h-1.2v3.252h2.4v-3.252zm0 3.252h-1.2a1 1 0 0 1 1.553-.833l-.664 1-.663 1c.933.619 2.174-.053 2.174-1.167zm-.31.167.665-.998-1.69-1.127-.665.998-.666.998 1.69 1.127zM14 12.666h-1.2V14.5h2.4v-1.834zm0 1.834h-1.2a.7.7 0 0 1 .7-.7v2.4a1.7 1.7 0 0 0 1.7-1.7zm-.5.5v-1.2h-5v2.4h5zm-5 0v-1.2a.7.7 0 0 1 .7.7H6.8a1.7 1.7 0 0 0 1.7 1.7zm-.5-.5h1.2v-5H6.8v5zm0-5h1.2a.7.7 0 0 1-.7.7V7.8a1.7 1.7 0 0 0-1.7 1.7zm.5-.5v1.2h5V7.8h-5z" mask="url(#a)" />
    </IconBase>
  )
}

IconDefaultAssets.displayName = "IconDefaultAssets"
