// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconComment(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="#F5F5F7" strokeWidth={1.5} d="M4 19.118V5.5a.5.5 0 0 1 .5-.5h15a.5.5 0 0 1 .5.5v11.222a.5.5 0 0 1-.5.5H8.783a.5.5 0 0 0-.256.071l-3.77 2.255a.5.5 0 0 1-.757-.43Z" />
    </IconBase>
  )
}

IconComment.displayName = "IconComment"
