// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSaved(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path stroke="#F5F5F7" strokeWidth={1.5} d="M5 19.084V5.5a.5.5 0 0 1 .5-.5h13a.5.5 0 0 1 .5.5v13.584a.5.5 0 0 1-.77.42l-5.96-3.83a.5.5 0 0 0-.54 0l-5.96 3.83a.5.5 0 0 1-.77-.42Z" />
    </IconBase>
  )
}

IconSaved.displayName = "IconSaved"
