// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconItalicFont(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M18.25 4.25a.5.5 0 0 1 .5.5v.5a.5.5 0 0 1-.5.5h-9.5a.5.5 0 0 1-.5-.5v-.5a.5.5 0 0 1 .5-.5z" /><path fill="currentColor" d="m14.232 5.663-3 13.5-1.464-.326 3-13.5z" /><path fill="currentColor" d="M15.25 18.25a.5.5 0 0 1 .5.5v.5a.5.5 0 0 1-.5.5h-9.5a.5.5 0 0 1-.5-.5v-.5a.5.5 0 0 1 .5-.5z" />
    </IconBase>
  )
}

IconItalicFont.displayName = "IconItalicFont"
