// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconSingleImage9GridInference(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M4 20.5a.5.5 0 0 1-.5-.5V4a.5.5 0 0 1 .5-.5h16a.5.5 0 0 1 .5.5v16a.5.5 0 0 1-.5.5zM5 19h14V5H5z" /><path fill="currentColor" d="M19.5 8.75v1.5H4v-1.5z" /><path fill="currentColor" d="M10.25 19.5h-1.5V4h1.5zM15.25 19.5h-1.5V4h1.5z" /><path fill="currentColor" d="M19.5 13.75v1.5H4v-1.5z" />
    </IconBase>
  )
}

IconSingleImage9GridInference.displayName = "IconSingleImage9GridInference"
