// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconNoPin(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <g fill="currentColor" clipPath="url(#a)"><path d="M17.537 3.547 7.647 20.38l-1.294-.76 9.89-16.833zM16.69 9.809l2.503 1.668c.348.232.557.623.557 1.04v1.733c0 .69-.56 1.25-1.25 1.25h-5.75v5.25h-1.5v-3.229L13.32 14h4.93v-1.349l-2.941-1.96-.01-.061 1.203-2.047zM13.422 4.5H9.644l-.903 5.864-.05.326-2.941 1.961V14h2.09l-.882 1.5H5.5c-.69 0-1.25-.56-1.25-1.25v-1.732c0-.418.209-.809.557-1.04l2.502-1.67.884-5.748A1.25 1.25 0 0 1 9.43 3h4.874z" /></g><defs><clipPath id="a"><path fill="currentColor" d="M0 0h24v24H0z" /></clipPath></defs>
    </IconBase>
  )
}

IconNoPin.displayName = "IconNoPin"
