// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconNumberedList(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M20 11.25v1.5H10v-1.5zM20 18.25v1.5H10v-1.5zM20 4.25v1.5H10v-1.5zM3 11.224v-1.008h1.344V5.294H3.21V4.52q.47-.084.806-.202.345-.126.639-.319h.915v6.216h1.168v1.008zM3.067 19.7v-.714a21 21 0 0 0 1.445-1.403q.604-.646.924-1.201.32-.562.32-1.042 0-.302-.11-.529a.76.76 0 0 0-.32-.344.94.94 0 0 0-.503-.126q-.336 0-.622.193a2.7 2.7 0 0 0-.512.445L3 14.316q.437-.471.89-.706.462-.244 1.092-.244.588 0 1.025.244.446.235.689.664.244.428.244 1.008 0 .562-.286 1.15a6 6 0 0 1-.748 1.16q-.47.58-1.041 1.142.244-.034.52-.05.286-.026.505-.026h1.344V19.7z" />
    </IconBase>
  )
}

IconNumberedList.displayName = "IconNumberedList"
