// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconTextEdite(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M15 8.5V10H9V8.5z" /><path fill="currentColor" d="M12.75 15.5h-1.5v-6h1.5z" /><path fill="currentColor" d="M19.864 6.999a.5.5 0 0 1 .136.342V12h-1.5V7.736L15.462 4.5H5.5v15H10V21H4.5l-.1-.01a.5.5 0 0 1-.4-.49v-17a.5.5 0 0 1 .5-.5h11.611zM12.024 19.943l-.655 1.24h1.5l8.845-5.76-.845-1.24zM17.369 19.683H20v1.5h-2.631z" />
    </IconBase>
  )
}

IconTextEdite.displayName = "IconTextEdite"
