// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function IconArrow(props: IconProps) {
  return (
    <IconBase viewBox="0 0 24 24" {...props}>
      <path fill="currentColor" d="M17.654 7.686 7.063 18.307 6 17.25 16.591 6.627z" /><path fill="currentColor" d="M18.31 15.716h-1.5V7.5H8.593V6h9.715z" />
    </IconBase>
  )
}

IconArrow.displayName = "IconArrow"
