/**
 * 把 public/raw-svg/<PascalCase>.svg 转成 registry/icons/Icon<PascalCase>.tsx，
 * 同时把每个图标作为 registry:ui 注入 registry.json 的 items。
 *
 * 命名约定（设计师与工程双向友好）：
 *   - SVG 文件：raw-svg/Model3D.svg     ← Figma 上 component 名直接落盘（sync-figma 保证）
 *   - 组件名 ：IconModel3D              ← "Icon" + Figma name
 *   - 文件名 ：IconModel3D.tsx          ← 同组件名
 *   - registry slug ：icon-model3d      ← 组件名小写化，给 shadcn CLI 用，无需可读
 *
 * 流程：
 *   1. 用 @svgr/core 把原始 SVG 跑一遍 svgo + jsx 生成「中间产物」
 *      （此时是一个标准的 <svg>...</svg> 函数组件）
 *   2. 用正则从中间产物里提取 <svg> 内部的 jsx 子节点
 *   3. 套上自定义模板：复用 components/icons/icon-base 的 IconBase 容器，
 *      把提取出来的子节点直接塞进去，避免运行时再构造一个被丢弃的 svg
 *   4. 扫产物列表写入 registry.json
 */
import { readdir, readFile, writeFile, mkdir, rm, copyFile } from "node:fs/promises";
import path from "node:path";
import { transform } from "@svgr/core";
import jsxPlugin from "@svgr/plugin-jsx";
import svgoPlugin from "@svgr/plugin-svgo";

const ROOT = path.resolve(__dirname, "..");
const RAW_DIR = path.join(ROOT, "public/raw-svg");
const OUT_DIR = path.join(ROOT, "registry/icons");
const MIRROR_DIR = path.join(ROOT, "components/icons");
const ICON_OVERRIDES_DIR = path.join(ROOT, "registry/icon-overrides");
const ICON_BASE_SRC = path.join(ROOT, "registry/lib/icon-base.tsx");
const REGISTRY_FILE = path.join(ROOT, "registry.json");
const META_FILE = path.join(ROOT, "components/icons-meta.json");

const REGISTRY_BASE_URL =
  process.env.REGISTRY_BASE_URL?.replace(/\/$/, "") || "https://az8.design";

const ICON_COMPONENT_OVERRIDES = [
  {
    pascalName: "Loading",
    componentName: "IconLoading",
    outName: "IconLoading.tsx",
    registryName: "icon-loading",
    viewBox: "0 0 24 24",
    inner: "__ICON_COMPONENT_OVERRIDE_LOADING__",
    preview: "loading",
  },
] as const;

const ICON_COMPONENT_OVERRIDE_NAMES = new Set(
  ICON_COMPONENT_OVERRIDES.flatMap((icon) => [
    icon.pascalName.toLowerCase(),
    icon.componentName.replace(/^Icon/, "").toLowerCase(),
  ]),
);

/** SVG 文件名已是 PascalCase（由 sync-figma 保证），剥掉扩展名就是图标名 */
function stripExt(filename: string) {
  return filename.replace(/\.svg$/i, "");
}

/** 给 shadcn CLI 用的 slug：保持机械小写，不拆词。Model3D → icon-model3d */
function toRegistrySlug(pascal: string) {
  return `icon-${pascal.toLowerCase()}`;
}

/** 从 svgr 中间产物里抠出 <svg ...>{children}</svg> 的 children + viewBox */
function extractSvgInner(code: string): { viewBox: string; inner: string } {
  const viewBoxMatch = code.match(/viewBox=["']([^"']+)["']/);
  const viewBox = viewBoxMatch ? viewBoxMatch[1] : "0 0 24 24";

  // 匹配 <svg ...>(.*)</svg>，dotAll
  const svgMatch = code.match(/<svg[^>]*?>([\s\S]*?)<\/svg>/);
  if (!svgMatch) {
    throw new Error("svgr 中间产物里找不到 <svg>...</svg>");
  }
  return { viewBox, inner: svgMatch[1].trim() };
}

/**
 * 把可见图形节点的 fill / stroke 语义化为 currentColor。
 * 保留 none、url(...) 和 <mask fill="#fff"> 这类结构性填充。
 */
function replaceVisiblePaintWithCurrentColor(inner: string) {
  return inner.replace(/<([A-Za-z][\w:-]*)([^<>]*?)>/g, (tag, name, attrs) => {
    if (name === "mask") return tag;
    return `<${name}${attrs.replace(
      /\b(fill|stroke)=(["'])(?!none\2|url\()[^"']+\2/g,
      '$1="currentColor"',
    )}>`;
  });
}

function assertSupportedSvg(svg: string, filename: string) {
  if (/<foreignObject\b|data-figma-gradient-fill/.test(svg)) {
    throw new Error(
      `${filename} contains Figma gradient/foreignObject SVG output. Add it to ICON_COMPONENT_OVERRIDES and provide a component override instead.`,
    );
  }
}

interface BuildResult {
  componentName: string;
  outName: string;
  registryName: string;
  viewBox: string;
  inner: string;
  preview?: string;
}

async function buildOne(svgPath: string): Promise<BuildResult> {
  const filename = path.basename(svgPath);
  const pascalName = stripExt(filename);
  const componentName = `Icon${pascalName}`;
  const outName = `${componentName}.tsx`;
  const registryName = toRegistrySlug(pascalName);

  const svg = await readFile(svgPath, "utf8");
  assertSupportedSvg(svg, filename);

  // 第一步：svgr 走 svgo + jsx，得到标准的 <svg> 组件源
  //
  // 颜色语义化：把可见图形节点的任意 fill / stroke 色值转成 currentColor。
  // 不用 SVGR replaceAttrValues，避免误伤 mask 等结构性填充。
  //
  // svgo 只做结构性清理：
  //   - removeDimensions: 去掉硬编码的 width/height，让 IconBase 的 size 生效
  //   - preset-default: 通用清理（注意要保留 viewBox）
  const intermediate = await transform(
    svg,
    {
      typescript: true,
      jsxRuntime: "automatic",
      icon: true,
      svgo: true,
      svgoConfig: {
        plugins: [
          {
            name: "preset-default",
            params: { overrides: { removeViewBox: false } },
          },
          "removeDimensions",
        ],
      },
      plugins: [svgoPlugin, jsxPlugin],
    },
    { componentName },
  );

  const { viewBox, inner: extractedInner } = extractSvgInner(intermediate);
  const inner = replaceVisiblePaintWithCurrentColor(extractedInner);

  // 第二步：套自己的模板
  const code = `// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.
import { IconBase, type IconProps } from "@/components/icons/icon-base"

export function ${componentName}(props: IconProps) {
  return (
    <IconBase viewBox="${viewBox}" {...props}>
      ${inner}
    </IconBase>
  )
}

${componentName}.displayName = "${componentName}"
`;

  await writeFile(path.join(OUT_DIR, outName), code, "utf8");

  return { componentName, outName, registryName, viewBox, inner };
}

async function main() {
  await rm(OUT_DIR, { recursive: true, force: true });
  await mkdir(OUT_DIR, { recursive: true });

  const files = (await readdir(RAW_DIR))
    .filter((f) => f.toLowerCase().endsWith(".svg"))
    .filter(
      (f) => !ICON_COMPONENT_OVERRIDE_NAMES.has(stripExt(f).toLowerCase()),
    )
    .sort();

  if (files.length === 0) {
    console.warn(`[build-icons] no svg in ${RAW_DIR}`);
  }

  const built: BuildResult[] = [];
  for (const f of files) {
    const result = await buildOne(path.join(RAW_DIR, f));
    built.push(result);
    console.log(`  ✓ ${f}  →  ${result.outName}  (${result.componentName})`);
  }
  for (const override of ICON_COMPONENT_OVERRIDES) {
    await copyFile(
      path.join(ICON_OVERRIDES_DIR, override.outName),
      path.join(OUT_DIR, override.outName),
    );
    built.push({ ...override });
    console.log(
      `  ◆ override:${override.pascalName}  →  ${override.outName}  (${override.componentName})`,
    );
  }

  // 同时把 IconBase 也复制一份到 registry/icons/，作为目录入口
  // 这样 import { IconArrowRight, IconBase } from "az8-ui/icons" 之类的用法可行
  // 但 registry items 的 path 仍然指向 registry/lib/icon-base.tsx 作为权威源
  const indexBody =
    `// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.\n` +
    `export { IconBase, type IconProps } from "@/registry/lib/icon-base"\n` +
    built
      .map((b) => `export * from "./${b.outName.replace(/\.tsx$/, "")}"`)
      .join("\n") +
    "\n";
  await writeFile(path.join(OUT_DIR, "index.ts"), indexBody, "utf8");

  // 写 registry.json
  const items = [
    {
      name: "icon-base",
      type: "registry:lib",
      title: "Icon Base",
      description:
        "AZ8 图标基础容器：统一 size / color / a11y 行为。所有 az8-ui 图标都依赖它。",
      files: [
        {
          path: "registry/lib/icon-base.tsx",
          type: "registry:lib",
          target: "components/icons/icon-base.tsx",
        },
      ],
    },
    ...built.map((b) => ({
      name: b.registryName,
      type: "registry:ui",
      title: b.componentName,
      description: `AZ8 图标：${b.componentName}`,
      // 跨仓库依赖必须用绝对 URL。本地开发时 export REGISTRY_BASE_URL=http://localhost:3000；
      // 生产用 https://az8.design（或 Vercel 部署 URL）。
      registryDependencies: [`${REGISTRY_BASE_URL}/r/icon-base.json`],
      files: [
        {
          path: `registry/icons/${b.outName}`,
          type: "registry:ui",
          target: `components/icons/${b.outName}`,
        },
      ],
    })),
  ];

  const registry = {
    $schema: "https://ui.shadcn.com/schema/registry.json",
    name: "az8-ui",
    homepage: REGISTRY_BASE_URL,
    items,
  };

  await writeFile(
    REGISTRY_FILE,
    JSON.stringify(registry, null, 2) + "\n",
    "utf8",
  );

  // 把产物镜像到 components/icons/，让本仓库的 docs 页能直接 import
  // （registry items 的 target 是消费方安装时落点，不是本仓库的 import 路径）
  await rm(MIRROR_DIR, { recursive: true, force: true });
  await mkdir(MIRROR_DIR, { recursive: true });
  await copyFile(ICON_BASE_SRC, path.join(MIRROR_DIR, "icon-base.tsx"));
  for (const b of built) {
    await copyFile(
      path.join(OUT_DIR, b.outName),
      path.join(MIRROR_DIR, b.outName),
    );
  }
  await writeFile(
    path.join(MIRROR_DIR, "index.ts"),
    `// AUTO-GENERATED by scripts/build-icons.ts — DO NOT EDIT.\n` +
      `export { IconBase, type IconProps } from "./icon-base"\n` +
      built
        .map((b) => `export * from "./${b.outName.replace(/\.tsx$/, "")}"`)
        .join("\n") +
      "\n",
    "utf8",
  );

  // 写 meta JSON：图标浏览器页用它做搜索 / 复制 SVG / 复制 JSX
  // viewBox + inner 是 JSX 形式（驼峰属性、自闭合 tag），可直接在 React 里当 dangerouslySetInnerHTML
  // 来做"复制 SVG"按钮时再转回 HTML 形式
  const meta = {
    icons: built.map((b) => ({
      registryName: b.registryName,
      componentName: b.componentName,
      viewBox: b.viewBox,
      inner: b.inner,
      preview: b.preview,
    })),
  };
  await writeFile(META_FILE, JSON.stringify(meta, null, 2) + "\n", "utf8");

  console.log(
    `\n[build-icons] generated ${built.length} icons + 1 base, registry.json + icons-meta.json updated, mirrored to components/icons/.`,
  );
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
